version: "3.3"

services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: somewordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8181:80"
    restart: always
    env_file:
      - envfile
    volumes:
      - "./wordpress:/var/www/html"
      - ".:/root"
      - "./site.conf:/etc/apache2/sites-available/000-default.conf"
    extra_hosts:
      - "apps.memberful.localhost:host-gateway"
      - "ttf.memberful.localhost:host-gateway"
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - cache:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cache: {}
  db_data: {}
